### ISSUE TITLE
Libra Merchant image url in README.md return 404

### ISSUE THREAD

**Issue by suraneti** [kulapio/libra-merchant#10]
Could you please check `Libra Merchant image URL` in README.md

source link: https://raw.githubusercontent.com/kulapio/libra-merchant/master/src/assets/img/logo/app-logo2.jpg?token=AADQJCDTUGZOUL4MN4SUD7C5ICDPC

**Comment by suraneti** [comment]
Maybe use this [link](https://raw.githubusercontent.com/kulapio/libra-merchant/master/src/assets/img/logo/app-logo.jpg?token=AADQJCDTUGZOUL4MN4SUD7C5ICDPC) instead.

**Comment by totiz** [comment]
Thanks done merged
